{% set version = "1.3.0" %}

package:
  name: libxmlsec1
  version: {{ version }}

source:
  url: https://www.aleksey.com/xmlsec/download/xmlsec1-{{ version }}.tar.gz
  sha256: df3ad2548288411fc3d44c20879e4c4e90684a1a4fb76a06ae444f957171c9a6

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # compatibility is not tracked at abi-laboratory, assume same as libxml2
    - {{ pin_subpackage('libxmlsec1', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make
  host:
    - icu
    - libgcrypt
    - libgpg-error
    - libiconv
    - libtool
    - libxml2
    - libxslt
    - openssl
    - xz
    - zlib
  run:
    # libltdl is linked, which the libtool package provides.
    # This is needed to enable dynamic loading support for xmlsec-crypto
    # libraries (--enable-crypto-dl option).
    - {{ pin_compatible('libtool') }}
    - {{ pin_compatible('xz') }}
    - {{ pin_compatible('zlib') }}

test:
  commands:
    - xmlsec1 --help

about:
  home: https://www.aleksey.com/xmlsec/
  license: MIT and MPL-1.1
  license_family: MIT
  license_file: Copyright
  summary: XML Security Library
  dev_url: https://github.com/lsh123/xmlsec

extra:
  recipe-maintainers:
    - xhochy
    - jaimergp
