{% set version = "1.2.31" %}

package:
  name: libxmlsec1
  version: {{ version }}

source:
  url: https://www.aleksey.com/xmlsec/download/xmlsec1-{{ version }}.tar.gz
  sha256: 9b10bc52cc31e4f76162e3975e50db26b71ab49c571d810b311ca626be5a0b26

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # compatibility is not tracked at abi-laboratory, assume same as libxml2
    - {{ pin_subpackage('libxmlsec1', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - icu
    - libgcrypt
    - libgpg-error
    - libiconv
    - libtool
    - libxml2
    - libxslt
    - openssl
    - xz
    - zlib
  run:
    # libltdl is linked, which the libtool package provides.
    # This is needed to enable dynamic loading support for xmlsec-crypto
    # libraries (--enable-crypto-dl option).
    - {{ pin_compatible('libtool') }}
    - {{ pin_compatible('xz') }}
    - {{ pin_compatible('zlib') }}

test:
  commands:
    - xmlsec1 --help

about:
  home: https://www.aleksey.com/xmlsec/
  license: MIT and MPL-1.1
  license_family: MIT
  license_file: Copyright
  summary: XML Security Library
  dev_url: https://github.com/lsh123/xmlsec

extra:
  recipe-maintainers:
    - jaimergp
