context:
  name: libxmlsec1
  version: '1.3.7'

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/lsh123/xmlsec/releases/download/${{ version }}/xmlsec1-${{ version }}.tar.gz
  sha256: d82e93b69b8aa205a616b62917a269322bf63a3eaafb3775014e61752b2013ea

build:
  number: 1
  skip: win

requirements:
  run_exports:
    # compatibility is not tracked at abi-laboratory, assume same as libxml2
    - ${{ pin_subpackage('libxmlsec1', upper_bound='x.x') }}
  build:
    - if: unix
      then:
        - gnuconfig
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - make
  host:
    - icu
    - libgcrypt
    - libgpg-error
    - libiconv
    - libtool
    - libxml2
    - libxslt
    - openssl
    - liblzma-devel
    - zlib
  run:
    # libltdl is linked, which the libtool package provides.
    # This is needed to enable dynamic loading support for xmlsec-crypto
    # libraries (--enable-crypto-dl option).
    - ${{ pin_compatible('libtool') }}
    - ${{ pin_compatible('zlib') }}

tests:
  - script: xmlsec1 --help

about:
  homepage: https://aleksey.com/xmlsec
  license: MIT AND MPL-1.1
  license_file: Copyright
  summary: XML Security Library
  repository: https://github.com/lsh123/xmlsec

extra:
  recipe-maintainers:
    - xhochy
    - jaimergp
